In [1]:
import pandas as pd
dataset=pd.read_csv(r'C:\Users\taner\Desktop\testdeneme2.csv')
dataset

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,mazda,3,1.6 impressive,2011,benzin & lpg,otomatik,183000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,124.800 TL
1,mazda,323,1.6 familia,1993,benzin & lpg,manuel,338000,90 hp,1597 cc,onden cekis,sahibinden,ikinci el,29.000 TL
2,mazda,323,1.6 familia,1993,benzin & lpg,manuel,250000,90 hp,1597 cc,onden cekis,galeriden,ikinci el,27.500 TL
3,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,102500,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,143.000 TL
4,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,218000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,102.000 TL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,mazda,3,1.6 d touring,2012,dizel,manuel,219000,115 hp,1560 cc,onden cekis,galeriden,ikinci el,110.000 TL
541,mazda,626,1.6,1990,benzin & lpg,manuel,165381,76 - 100 hp,1301 - 1600 cm3,arkadan itis,sahibinden,ikinci el,36.500 TL
542,mazda,626,2.0,1998,benzin & lpg,manuel,237000,115 hp,1991 cc,onden cekis,sahibinden,ikinci el,57.500 TL
543,mazda,3,1.5 skyactive-g reflex,2014,benzin,otomatik,77500,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,214.000 TL
544,mazda,mx,mx-5 1.5,2018,benzin,manuel,14529,131 hp,1496 cc,arkadan itis,galeriden,ikinci el,349.850 TL

In [ ]:
dataset = dataset.astype({"yil":object ,"km":object})
dataset

In [3]:
writer = pd.ExcelWriter(r'C:\Users\taner\Desktop\MakineOgrenmesi\veriSeti.xlsx', engine='xlsxwriter')
dataset.to_excel(writer, sheet_name='On Isleme Oncesi Veriseti',index = False)
writer.save()

In [2]:
dataset=dataset.dropna()
dataset = dataset.reset_index(drop=True)

In [3]:
dataset[dataset.isna().any(axis=1)]

Empty DataFrame
Columns: [marka, seri, model, yil, yakit, vites, km, motor gucu, motor hacmi, cekis, kimden, durumu, fiyat]
Index: []

In [4]:
dataset["marka"].value_counts()

mazda    545
Name: marka, dtype: int64

In [5]:
dataset["seri"].value_counts()

3          202
323        144
626         94
6           29
rx          20
lantis      18
2           14
mx          13
5            3
xedos        3
mpv          2
premacy      1
929          1
121          1
Name: seri, dtype: int64

In [5]:
dataset["model"].value_counts()

2.0                            82
1.6 impressive                 43
1.6 glx                        42
1.6 touring                    33
1.5 1.5i                       28
1.6 dynamic                    27
1.6 1.6i                       24
rx-8                           19
1.8                            19
1.5 familia                    16
1.5 skyactive-g power          15
1.6 d touring                  14
1.6                            13
mx-5 1.5                       11
1.5 skyactive-g power sense    10
1.5 skyactive-g reflex         10
1.5 practica                   10
2.0 sport                       9
1.6 familia                     9
1.8 familia                     9
1.6 sport dynamic               7
2.0 dynamic                     7
1.5 skyactive-d power           6
1.6 d impressive                6
2.0 te                          5
1.5 skyactive-d reflex          5
1.6 d comfort                   5
1.5 go                          5
1.5 skyactive-g motion          5
2.0 exclusive                   4
1.6 gl                          4
6                               3
1.6 sport                       3
1.5 sport                       3
1.3 go                          2
1.3 high                        2
1.6 base                        2
2.0 sky-g power                 2
1.5 skyactive-d motion          2
2.0 mid                         2
1.5 skyactive-g soul            2
1.5 skyactive-d power sense     2
1.6 comfort                     2
1.6 90. yil                     2
1.5 fun                         1
mx-5 2.0                        1
13 go                           1
1.8 1.8i                        1
1.6 mid                         1
1.6 high                        1
1.6 sport comfort               1
2.0 glx                         1
1.3                             1
1.8 gt                          1
3.0i v6                         1
mx-5 1.8                        1
1.6 sport ce                    1
rx-7                            1
Name: model, dtype: int64

In [6]:
dataset["yakit"].value_counts()

benzin & lpg    377
benzin          124
dizel            44
Name: yakit, dtype: int64

In [7]:
dataset["motor gucu"].value_counts()

105 hp            132
88 hp              80
115 hp             56
90 hp              51
120 hp             39
76 - 100 hp        25
101 - 125 hp       20
131 hp             14
122 hp             14
231 hp             14
147 hp             12
117 hp              9
109 hp              8
103 hp              7
165 hp              7
126 - 150 hp        7
141 hp              6
86 hp               4
114 hp              4
192 hp              4
51 - 75 hp          4
176 - 200 hp        3
136 hp              3
140 hp              3
116 hp              3
155 hp              2
102 hp              2
50 hp'ye kadar      2
151 - 175 hp        2
144 hp              1
50 hp               1
100 hp              1
160 hp              1
226 - 250 hp        1
98 hp               1
128 hp              1
154 hp              1
Name: motor gucu, dtype: int64

In [8]:
dataset["motor hacmi"].value_counts()

1598 cc              124
1597 cc               53
1991 cc               52
1496 cc               50
1998 cc               35
1301 - 1600 cm3       31
1498 cc               29
1560 cc               28
1489 cc               26
1840 cc               22
1999 cc               21
1308 cc               18
1601 - 1800 cm3       17
1499 cc               14
1801 - 2000 cm3       10
1349 cc                4
1300 cm3' e kadar      4
1995 cc                3
1299 cc                1
2954 cc                1
2501 - 3000 cm3        1
2001 - 2500 cm3        1
Name: motor hacmi, dtype: int64

In [9]:
dataset["cekis"].value_counts()

onden cekis     506
arkadan itis     39
Name: cekis, dtype: int64

In [10]:
dataset["kimden"].value_counts()

sahibinden    413
galeriden     132
Name: kimden, dtype: int64

In [11]:
dataset["durumu"].value_counts()

ikinci el    544
sifir          1
Name: durumu, dtype: int64

In [15]:
pd.get_dummies(dataset["seri"],prefix = 'seri')

,seri_121,seri_2,seri_3,seri_323,seri_5,seri_6,seri_626,seri_929,seri_lantis,seri_mpv,seri_mx,seri_premacy,seri_rx,seri_xedos
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,0,0,1,0,0,0,0,0,0,0,0,0,0,0
541,0,0,0,0,0,0,1,0,0,0,0,0,0,0
542,0,0,0,0,0,0,1,0,0,0,0,0,0,0
543,0,0,1,0,0,0,0,0,0,0,0,0,0,0
544,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [6]:
from sklearn import preprocessing
lbe = preprocessing.LabelEncoder()

In [7]:
def labelEncNameMap(lbe,dataset):
    lbe.fit(dataset)
    lbe_name_mapping = dict(zip(lbe.classes_, lbe.transform(lbe.classes_)))
    print(lbe_name_mapping)

In [19]:
labelEncNameMap(lbe,dataset["durumu"])

{'ikinci el': 0, 'sifir': 1}

In [26]:
dataset

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,mazda,3,1.6 impressive,2011,benzin & lpg,otomatik,183000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,124.800 TL
1,mazda,323,1.6 familia,1993,benzin & lpg,manuel,338000,90 hp,1597 cc,onden cekis,sahibinden,ikinci el,29.000 TL
2,mazda,323,1.6 familia,1993,benzin & lpg,manuel,250000,90 hp,1597 cc,onden cekis,galeriden,ikinci el,27.500 TL
3,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,102500,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,143.000 TL
4,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,218000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,102.000 TL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,mazda,3,1.6 d touring,2012,dizel,manuel,219000,115 hp,1560 cc,onden cekis,galeriden,ikinci el,110.000 TL
541,mazda,626,1.6,1990,benzin & lpg,manuel,165381,76 - 100 hp,1301 - 1600 cm3,arkadan itis,sahibinden,ikinci el,36.500 TL
542,mazda,626,2.0,1998,benzin & lpg,manuel,237000,115 hp,1991 cc,onden cekis,sahibinden,ikinci el,57.500 TL
543,mazda,3,1.5 skyactive-g reflex,2014,benzin,otomatik,77500,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,214.000 TL
544,mazda,mx,mx-5 1.5,2018,benzin,manuel,14529,131 hp,1496 cc,arkadan itis,galeriden,ikinci el,349.850 TL

In [9]:
datasetPre=pd.DataFrame()
datasetPre["marka"]=lbe.fit_transform(dataset['marka'])
datasetPre

     marka
0        0
1        0
2        0
3        0
4        0
..     ...
540      0
541      0
542      0
543      0
544      0

[545 rows x 1 columns]

In [10]:
datasetPre["seri"]=lbe.fit_transform(dataset['seri'])
datasetPre

     marka  seri
0        0     2
1        0     3
2        0     3
3        0     2
4        0     2
..     ...   ...
540      0     2
541      0     6
542      0     6
543      0     2
544      0    10

[545 rows x 2 columns]

In [11]:
datasetPre["model"]=lbe.fit_transform(dataset['model'])
datasetPre

     marka  seri  model
0        0     2     31
1        0     3     27
2        0     3     27
3        0     2     31
4        0     2     31
..     ...   ...    ...
540      0     2     25
541      0     6     18
542      0     6     42
543      0     2     15
544      0    10     52

[545 rows x 3 columns]

In [70]:
datasetPre["yil"]=dataset['yil']
datasetPre

     marka  seri  model     yil  yakit  vites        km motor gucu
0        0     2     31  2011.0      1      1  183000.0        105
1        0     3     27  1993.0      1      0  338000.0         90
2        0     3     27  1993.0      1      0  250000.0         90
3        0     2     31  2010.0      1      1  102500.0        105
4        0     2     31  2010.0      1      1  218000.0        105
..     ...   ...    ...     ...    ...    ...       ...        ...
540      0     2     25  2012.0      2      0     224.0        115
541      0     6     18  1990.0      1      0  238000.0         88
542      0     6     43  1998.0      1      0  300000.0        115
543      0     2     15  2014.0      0      1  313000.0        120
544      0    10     53  2018.0      0      0  194000.0        131

[545 rows x 8 columns]

In [37]:
datasetPre["yakit"]=lbe.fit_transform(dataset['yakit'])
datasetPre

     marka  seri  model     yil  yakit
0        0     2     31  2011.0      1
1        0     3     27  1993.0      1
2        0     3     27  1993.0      1
3        0     2     31  2010.0      1
4        0     2     31  2010.0      1
..     ...   ...    ...     ...    ...
540      0     2     25  2011.0      2
541      0     6     18  2004.0      1
542      0     6     43  1997.0      1
543      0     2     15  1999.0      0
544      0    10     53  2007.0      0

[545 rows x 5 columns]

In [38]:
datasetPre["vites"]=lbe.fit_transform(dataset['vites'])
datasetPre

     marka  seri  model     yil  yakit  vites
0        0     2     31  2011.0      1      1
1        0     3     27  1993.0      1      0
2        0     3     27  1993.0      1      0
3        0     2     31  2010.0      1      1
4        0     2     31  2010.0      1      1
..     ...   ...    ...     ...    ...    ...
540      0     2     25  2011.0      2      0
541      0     6     18  2004.0      1      0
542      0     6     43  1997.0      1      0
543      0     2     15  1999.0      0      1
544      0    10     53  2007.0      0      0

[545 rows x 6 columns]

In [1]:
datasetPre["km"]=dataset['km']
datasetPre

NameError: name 'dataset' is not defined

In [65]:
guc=[]
for x in dataset["motor gucu"]:
    if "-" not in x:
        guc.append(x.split()[0])
    else:
        guc.append((float(x.split()[0])+float(x.split()[2]))/2.0)
datasetPre["motor gucu"]=guc
datasetPre

     marka  seri  model     yil  yakit  vites        km motor gucu
0        0     2     31  2011.0      1      1  183000.0        105
1        0     3     27  1993.0      1      0  338000.0         90
2        0     3     27  1993.0      1      0  250000.0         90
3        0     2     31  2010.0      1      1  102500.0        105
4        0     2     31  2010.0      1      1  218000.0        105
..     ...   ...    ...     ...    ...    ...       ...        ...
540      0     2     25  2011.0      2      0     224.0        115
541      0     6     18  2004.0      1      0  238000.0         88
542      0     6     43  1997.0      1      0  300000.0        115
543      0     2     15  1999.0      0      1  313000.0        120
544      0    10     53  2007.0      0      0  194000.0        131

[545 rows x 8 columns]

In [72]:
hacim=[]
for x in dataset["motor hacmi"]:
    if "-" not in x:
        hacim.append(x.split()[0])
    else:
        hacim.append((float(x.split()[0])+float(x.split()[2]))/2.0)
datasetPre["motor hacmi"]=hacim
datasetPre

     marka  seri  model     yil  yakit  vites        km motor gucu motor hacmi
0        0     2     31  2011.0      1      1  183000.0        105        1598
1        0     3     27  1993.0      1      0  338000.0         90        1597
2        0     3     27  1993.0      1      0  250000.0         90        1597
3        0     2     31  2010.0      1      1  102500.0        105        1598
4        0     2     31  2010.0      1      1  218000.0        105        1598
..     ...   ...    ...     ...    ...    ...       ...        ...         ...
540      0     2     25  2012.0      2      0  219000.0        115        1560
541      0     6     18  1990.0      1      0  165381.0         88      1450.5
542      0     6     43  1998.0      1      0  237000.0        115        1991
543      0     2     15  2014.0      0      1   77500.0        120        1496
544      0    10     53  2018.0      0      0   14529.0        131        1496

[545 rows x 9 columns]

In [73]:
datasetPre["cekis"]=lbe.fit_transform(dataset['cekis'])
datasetPre

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis
0,0,2,31,2011.0,1,1,183000.0,105,1598,1
1,0,3,27,1993.0,1,0,338000.0,90,1597,1
2,0,3,27,1993.0,1,0,250000.0,90,1597,1
3,0,2,31,2010.0,1,1,102500.0,105,1598,1
4,0,2,31,2010.0,1,1,218000.0,105,1598,1
...,...,...,...,...,...,...,...,...,...,...
540,0,2,25,2012.0,2,0,219000.0,115,1560,1
541,0,6,18,1990.0,1,0,165381.0,88,1450.5,0
542,0,6,43,1998.0,1,0,237000.0,115,1991,1
543,0,2,15,2014.0,0,1,77500.0,120,1496,1
544,0,10,53,2018.0,0,0,14529.0,131,1496,0

In [74]:
datasetPre["kimden"]=lbe.fit_transform(dataset['kimden'])
datasetPre

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden
0,0,2,31,2011.0,1,1,183000.0,105,1598,1,0
1,0,3,27,1993.0,1,0,338000.0,90,1597,1,1
2,0,3,27,1993.0,1,0,250000.0,90,1597,1,0
3,0,2,31,2010.0,1,1,102500.0,105,1598,1,1
4,0,2,31,2010.0,1,1,218000.0,105,1598,1,0
...,...,...,...,...,...,...,...,...,...,...,...
540,0,2,25,2012.0,2,0,219000.0,115,1560,1,0
541,0,6,18,1990.0,1,0,165381.0,88,1450.5,0,1
542,0,6,43,1998.0,1,0,237000.0,115,1991,1,1
543,0,2,15,2014.0,0,1,77500.0,120,1496,1,1
544,0,10,53,2018.0,0,0,14529.0,131,1496,0,0

In [75]:
datasetPre["durumu"]=lbe.fit_transform(dataset['durumu'])
datasetPre

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu
0,0,2,31,2011.0,1,1,183000.0,105,1598,1,0,0
1,0,3,27,1993.0,1,0,338000.0,90,1597,1,1,0
2,0,3,27,1993.0,1,0,250000.0,90,1597,1,0,0
3,0,2,31,2010.0,1,1,102500.0,105,1598,1,1,0
4,0,2,31,2010.0,1,1,218000.0,105,1598,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,0,2,25,2012.0,2,0,219000.0,115,1560,1,0,0
541,0,6,18,1990.0,1,0,165381.0,88,1450.5,0,1,0
542,0,6,43,1998.0,1,0,237000.0,115,1991,1,1,0
543,0,2,15,2014.0,0,1,77500.0,120,1496,1,1,0
544,0,10,53,2018.0,0,0,14529.0,131,1496,0,0,0

In [79]:
datasetPre["fiyat"]=dataset["fiyat"].str.replace(" TL","")
datasetPre["fiyat"]=datasetPre["fiyat"].str.replace(".","")
datasetPre

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,0,2,31,2011.0,1,1,183000.0,105,1598,1,0,0,124800
1,0,3,27,1993.0,1,0,338000.0,90,1597,1,1,0,29000
2,0,3,27,1993.0,1,0,250000.0,90,1597,1,0,0,27500
3,0,2,31,2010.0,1,1,102500.0,105,1598,1,1,0,143000
4,0,2,31,2010.0,1,1,218000.0,105,1598,1,0,0,102000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,0,2,25,2012.0,2,0,219000.0,115,1560,1,0,0,110000
541,0,6,18,1990.0,1,0,165381.0,88,1450.5,0,1,0,36500
542,0,6,43,1998.0,1,0,237000.0,115,1991,1,1,0,57500
543,0,2,15,2014.0,0,1,77500.0,120,1496,1,1,0,214000
544,0,10,53,2018.0,0,0,14529.0,131,1496,0,0,0,349850

In [35]:
datasetPre.dtypes

NameError: name 'datasetPre' is not defined

In [83]:
datasetPre = datasetPre.astype({"yil":int ,"km":int,"motor gucu":float,"motor hacmi":float,"fiyat":int})

In [86]:
from openpyxl import load_workbook
book = load_workbook(r'C:\Users\taner\Desktop\MakineOgrenmesi1\veriSeti.xlsx')
writer = pd.ExcelWriter(r'C:\Users\taner\Desktop\MakineOgrenmesi1\veriSeti.xlsx', engine='openpyxl')
writer.book = book
datasetPre.to_excel(writer, sheet_name='Ön işleme sonrası veri',index = False)
writer.save()

In [39]:
attributes="a"

In [40]:
attributes

'a'