In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time
url="https://www.sahibinden.com/"
headersparam = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"}
urlMoney=[]
urls=[]
ozellikAd=[]

In [2]:
#Siteye belli bir istek atınca site otomatik olarak yanıt vermiyor ve belli bir süre beklemek gerekiyor
#Bu fonksiyonla site yanıt vermeyince otomatik olarak istek atıyor ve 1 dakika bekliyor 
#site yanıt verince program çalışmaya devam edebiliyor böylece
def tooManyRequestErrCheck():
    req = requests.get(url,headers=headersparam)
    d=0
    while(req.status_code == 429):
        d+=1
        req = requests.get(url,headers=headersparam)
        print(str(d))
        time.sleep(60)

In [3]:
#Siteden gelen önemsiz verileri listeden siliyor
#Verilerin önündeki boşlukları kaldırıyor ve Km verisindeki noktayı kaldırıyor
def popItem(itemList):
    itemList.pop(0)
    itemList.pop(0)
    itemList.pop(7)
    itemList.pop(10)
    itemList.pop(10)
    itemList.pop(10)
    itemList.pop(11)
    itemList.pop(11)
    for x in range(12):
        itemList[x]=strTrans(itemList[x].text).strip()
        if x==6:
            itemList[x]=itemList[x].replace('.', '')
    return itemList

In [4]:
#Arama sonucunda ilk sonucun sitesine gidip sütünların adlarını aliyor
# ve ilerki veriler için dataframein boş bir şekilde iskeletini oluşturuyor
def dataFrameMake():
    query="mazda?pagingOffset="+str(0)
    req = requests.get(url+query,headers=headersparam)
    soup = BeautifulSoup(req.text, "html.parser")
    c=soup.find("a", attrs={"class": "classifiedTitle"}).get('href')
    req = requests.get(url+c,headers=headersparam)
    soup= BeautifulSoup(req.text, "html.parser")
    ozellikAd=popItem(soup.find("ul","classifiedInfoList").findAll("strong"))
    df=pd.DataFrame(columns=ozellikAd)
    return df

In [5]:
#Siteden gelen verilerin türkçe karakterlerini ingilizce yapıyor ve yazıyı küçük harfli haline çeviriyor
def strTrans(str):
    s=str.maketrans("çğıöşüÇĞİÖŞÜ", "cgiosuCGIOSU")
    return str.translate(s).lower()

In [6]:
#Siteden toplayacağı verilerin urllerini bulmak için siteyi geziyor ve bunları fiyatlarıyla birlikte bir diziye atıyor
#Ve fiyatları dataframe koyuyor böylece dataframede satırları yapmış oluyor 
j=0
for i in range(0,350,50):
    query="mazda?pagingOffset="+str(i)+"&pagingSize=50"
    req = requests.get(url+query,headers=headersparam)
    if req.status_code==429:
        tooManyRequestErrCheck()
        req=requests.get(url+query,headers=headersparam)
    print(req.status_code)
    soup = BeautifulSoup(req.text, "html.parser")
    for link in soup.find_all("tr", attrs={"class": "searchResultsItem"}):
        if link.find("a","classifiedTitle")==None:
            continue
        urls.append(link.find("a","classifiedTitle").get("href"))
        urlMoney.append(link.find("td","searchResultsPriceValue").find("div").text.strip())
        j+=1
        print(str(j))
dataset=dataFrameMake()
dataset["fiyat"]=urlMoney

200
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
200
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
200
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
200
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
200
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
200
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350

In [7]:
#Siteden verileri topluyor ve onları dataframe tablosuna dolduruyor
for x in range(0,310):
    tooManyRequestErrCheck()
    req = requests.get(url+urls[x],headers=headersparam)
    if req.status_code==429:
        tooManyRequestErrCheck()
        req=requests.get(url+urls[x],headers=headersparam)
    if req.status_code!=200:
        print(str(x),url+urls[x])
        print("Hata Kodu: "+str(req.status_code))
        continue
    soup2 = BeautifulSoup(req.text, "html.parser")
    print(str(x),url+urls[x])
    if (soup2.find("ul","classifiedInfoList")==None):
        print("Hata Kodu: Veri Yok")
        continue
    ozellik=popItem(soup2.find("ul","classifiedInfoList").findAll("span"))
    for i in range(0,12): 
        dataset.iat[x,i]=ozellik[i]
    dataset.to_csv(r'C:\Users\taner\Desktop\172804014 Taner Filiz\testCsv.csv',index = False)

0 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-akyildiz-2.el-garantili-otomobiller-yeni-mazda3-skyd-reflex-6at-868446509/detay
1 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-akyildiz-2.el-garantili-otomobiller-mazda3-sky-g-power-sens-6at-872901586/detay
2 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-1.5-doch-motor-satilik-894051866/detay
3 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-1993-893251533/detay
4 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2016-mazda-3-dizel-otomatik-hatasiz-894048792/detay
5 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-eyk-motorsdan-mazda-323-878090921/detay
6 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-otomatik-masrafsiz-bakimli-touring-893988864/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
7 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sifir-sanziman-sifir-muayene-885770552/detay
8 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-3-power-1.5-skyactive-g-otomatik-sedan-893972655/detay
9 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-lantis-full-kasa-885711569/detay
10 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-4-ceker-jip-veya-pikapla-takasli-707181006/detay
11 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-nakit-fiyati-bu-takas-fiyati-degil-824060907/detay
12 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-xedos-9-876550680/detay
13 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-1.6-otomatic-kilimali-893924559/detay
14 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-cok-boyle-guzeli-yok...lpg-klima..full-893929782/detay
15 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-m50-3000-stroker-swap-rx-7-fc3s-893916056/detay
16 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sitenin-en-temizlerinden-874985675/detay
17 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-satilik-mazda-893883699/detay
18 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2015-mazda3-power-sense-otomatik-vites-genis-ekran-koltuk-isitma-893882963/detay
19 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-usak-merkezde-mazda-323-893886196/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
20 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-temizin-temizi-mi-ariyon-893863995/detay
21 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-6.26-modeline-gore-cok-temiz-893614083/detay
22 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-daha-iyisi-tokyo-da-893749665/detay
23 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-2-spor-893714606/detay
24 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-familia-873918691/detay
25 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-1.5-doch-motor-893750338/detay
26 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-masrafsiz-temiz-bakimli-aile-araci-893747204/detay
27 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-kazasiz-degisensiz-tam-otomatik-vites-mazda.6-lpgli.bose-muzik-885612673/detay
28 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-satilik-893736504/detay
29 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-altay-dan-2015-mazda-3-1.5-skyactive-g-rexlex-893753560/detay
30 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-satilik-orj.klimali-893711002/detay
31 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-120.000-km-otomatik-886260473/detay
32 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-ogretmenden-2012-otomatik-impressive-893706913/detay
33 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-acil-satilik-mazda-885008287/detay
34 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-ful-lantis-879121279/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
35 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-doch-1.8-motor-893711095/detay
36 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-1.5i-motor-323-otomatik-mazda-893715637/detay
37 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-orjinal-kusursuz-otomatik-mazda-lantis-893685492/detay
38 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-acill-otomotik-mazda-893699926/detay
39 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-arkadaslar-butun-ilanlara-bakin-bu-km-de-bu-orjinalde-esi-yok-874800706/detay
40 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-aysit-otomotiv-plaza-3-1.5-skyactive-g-motion-otomatik-743397349/detay
41 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-mazda-323-893664311/detay
42 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-kapali-goz-ilanda-hdled-double-teyp-klima-bakimli-893661002/detay
43 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-temiz-bakimli-vizesi-yeni-893657844/detay
44 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-ucuncu-sahibinden-mazda-mx-5-sport-858434970/detay
45 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-626.2.0-glx-abs-li-cift-hava-yastigi-79.000-km-de-893658774/detay
46 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2015-model-mazda-893648940/detay
47 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2010-otomatik-tr-nin-en-uygun-fiyatina-mazda-3-883007059/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
48 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-diri-kasa-mazda-626-893641286/detay
49 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-temiz-kullanilmis-mazda-626-893636117/detay
50 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-konya-dan-tertemiz-mazda-323-893638293/detay
51 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-temiz-mazda-626-890207574/detay
52 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-3-touring-858893100/detay
53 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-cankaya-otomotiv.mazda-323-familia.otomatik-vites.bakimli-877221206/detay
54 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-3-sahibinden-degisensiz-198-binde-893622744/detay
55 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2008-model-tam-otomatik-bakimli-868272197/detay
56 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-degisensiz-mazda-2.0-benzinli-136bg-889420808/detay
57 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-es-class-2001-makyajli-626-dijital-klima-abs-airbag-884067989/detay
58 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-hkc-auto-dan-mazda-6-dynamic-2.0-benzin-otomatik-893938051/detay
59 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-acil-satilik-893590046/detay
60 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2009-mazda-6-2.0-dynamic-otomatik-vites-171.000-km-de-885008292/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
61 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-yer-ucagi-893597536/detay
62 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-hyundai-bayi-hunko-dan-2003-mazda-323-otomatik-vites-177.500-km-877770899/detay
63 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-626-hacback-93-model-yer-ucagi-893590463/detay
64 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-otomatik-vites-mazda-323-sedan-masrafsiz-893590335/detay
65 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2017-mazda-3-otomatik-vitrs-ilkel-38.000-km-orjinal-884095365/detay
66 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323f-893561804/detay
67 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-ayasdan-cok-temiz-mazda-323-893559013/detay
68 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-ozturk-otomotivden-mazda-3-893548869/detay
69 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-acil-satilik-893539232/detay
70 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-biblo-893538047/detay
71 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2012-mazda-3-impressive-1.6d-115hp-kor-nokta-k.isitma-bayii-den-877570798/detay
72 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2005-mazda-3-1%2C6-comfort-lpg-li-877261083/detay
73 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-323-1992-model-893457457/detay
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
74 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-yuksek-modelle-takas-dusunulur-893446201/detay

75 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-6-sport-yetkili-servis-bakimli-142.000-km-893421713/detay
76 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-spor-araba-886281903/detay
77 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazda-626-japon-gemisi-temizz-893407521/detay
78 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-mazda-1.5-familia-893400937/detay
79 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-sahibinden-temiz-full-833377966/detay
80 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-2010-otomatik-mukemmel-temizlikte-mazda-3-lpgli-891432100/detay
81 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-mazdaspeed-893388223/detay
82 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-japon-harikasi-satista-873032399/detay
83 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-cok-temiz-mazda-626-894031845/detay
84 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-hatasiz-boyasiz-858149708/detay
85 https://www.sahibinden.com//ilan/vasita-otomobil-mazda-otomotik-klimali-masrafsiz-tertemiz-aile-araci-893341239/detay
1
2
3
4
5
6
7
8
9
10
11
12
13

KeyboardInterrupt:

In [8]:
dataset.to_csv('testCsv.csv',index = False)

In [9]:
dataset.head(10)

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,mazda,3,1.5 skyactive-d reflex,2017.0,dizel,otomatik,82884.0,105 hp,1499 cc,onden cekis,galeriden,ikinci el,239.900 TL
1,mazda,3,1.5 skyactive-g power sense,2016.0,benzin,otomatik,127863.0,120 hp,1496 cc,onden cekis,galeriden,ikinci el,195.900 TL
2,mazda,323,1.5 1.5i,2000.0,benzin & lpg,manuel,365000.0,126 - 150 hp,1301 - 1600 cm3,onden cekis,sahibinden,ikinci el,46.750 TL
3,mazda,323,1.6 glx,1993.0,benzin & lpg,manuel,403000.0,88 hp,1597 cc,onden cekis,sahibinden,ikinci el,31.500 TL
4,mazda,3,1.5 skyactive-d power sense,2016.0,dizel,otomatik,125000.0,105 hp,1499 cc,onden cekis,galeriden,ikinci el,237.000 TL
5,mazda,323,1.5 1.5i,2000.0,benzin & lpg,manuel,294000.0,88 hp,1489 cc,onden cekis,galeriden,ikinci el,56.500 TL
6,mazda,3,1.6 touring,2010.0,benzin & lpg,otomatik,248000.0,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,112.500 TL
7,mazda,lantis,1.8,1997.0,benzin & lpg,otomatik,25000.0,101 - 125 hp,1801 - 2000 cm3,onden cekis,galeriden,ikinci el,41.500 TL
8,mazda,3,1.5 skyactive-g power,2017.0,benzin,otomatik,29000.0,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,210.000 TL
9,mazda,lantis,1.8,1998.0,benzin & lpg,manuel,398000.0,122 hp,1840 cc,onden cekis,sahibinden,ikinci el,46.000 TL

## Yukardaki kısımlar tekrar çalıştırılıdığı için çok beklenmesin diye çalışırken durdurulduğu için tamamlanmıyor 
## Aşağadaki kısımda önceden 12 saat veri çekimi sonucu oluşan dataframe (Malesef csv dosyası silindi)

In [105]:
dataset

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,mazda,3,1.6 impressive,2011,benzin & lpg,otomatik,183000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,124.800 TL
1,mazda,323,1.6 familia,1993,benzin & lpg,manuel,338000,90 hp,1597 cc,onden cekis,sahibinden,ikinci el,29.000 TL
2,mazda,323,1.6 familia,1993,benzin & lpg,manuel,250000,90 hp,1597 cc,onden cekis,galeriden,ikinci el,27.500 TL
3,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,102500,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,143.000 TL
4,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,218000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,102.000 TL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,mazda,3,1.6 d touring,2012,dizel,manuel,219000,115 hp,1560 cc,onden cekis,galeriden,ikinci el,110.000 TL
549,mazda,626,1.6,1990,benzin & lpg,manuel,165381,76 - 100 hp,1301 - 1600 cm3,arkadan itis,sahibinden,ikinci el,36.500 TL
550,mazda,626,2.0,1998,benzin & lpg,manuel,237000,115 hp,1991 cc,onden cekis,sahibinden,ikinci el,57.500 TL
551,mazda,3,1.5 skyactive-g reflex,2014,benzin,otomatik,77500,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,214.000 TL
552,mazda,mx,mx-5 1.5,2018,benzin,manuel,14529,131 hp,1496 cc,arkadan itis,galeriden,ikinci el,349.850 TL

In [120]:
dataset.to_csv('veri.csv',index = False)

In [124]:
writer = pd.ExcelWriter('veriSetiurl.xlsx', engine='xlsxwriter')
dfs.to_excel(writer, sheet_name='Ön işleme öncesi veri',index = False)
writer.save()

In [118]:
dataset

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat
0,mazda,3,1.6 impressive,2011,benzin & lpg,otomatik,183000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,124.800 TL
1,mazda,323,1.6 familia,1993,benzin & lpg,manuel,338000,90 hp,1597 cc,onden cekis,sahibinden,ikinci el,29.000 TL
2,mazda,323,1.6 familia,1993,benzin & lpg,manuel,250000,90 hp,1597 cc,onden cekis,galeriden,ikinci el,27.500 TL
3,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,102500,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,143.000 TL
4,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,218000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,102.000 TL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,mazda,3,1.6 d touring,2012,dizel,manuel,219000,115 hp,1560 cc,onden cekis,galeriden,ikinci el,110.000 TL
549,mazda,626,1.6,1990,benzin & lpg,manuel,165381,76 - 100 hp,1301 - 1600 cm3,arkadan itis,sahibinden,ikinci el,36.500 TL
550,mazda,626,2.0,1998,benzin & lpg,manuel,237000,115 hp,1991 cc,onden cekis,sahibinden,ikinci el,57.500 TL
551,mazda,3,1.5 skyactive-g reflex,2014,benzin,otomatik,77500,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,214.000 TL
552,mazda,mx,mx-5 1.5,2018,benzin,manuel,14529,131 hp,1496 cc,arkadan itis,galeriden,ikinci el,349.850 TL

In [123]:
for x in range(len(urls)):
    urls[x]=url+urls[x]
dfs=dataset
dfs["urls"]=urls
dfs

,marka,seri,model,yil,yakit,vites,km,motor gucu,motor hacmi,cekis,kimden,durumu,fiyat,urls
0,mazda,3,1.6 impressive,2011,benzin & lpg,otomatik,183000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,124.800 TL,https://www.sahibinden.com//ilan/vasita-otomob...
1,mazda,323,1.6 familia,1993,benzin & lpg,manuel,338000,90 hp,1597 cc,onden cekis,sahibinden,ikinci el,29.000 TL,https://www.sahibinden.com//ilan/vasita-otomob...
2,mazda,323,1.6 familia,1993,benzin & lpg,manuel,250000,90 hp,1597 cc,onden cekis,galeriden,ikinci el,27.500 TL,https://www.sahibinden.com//ilan/vasita-otomob...
3,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,102500,105 hp,1598 cc,onden cekis,sahibinden,ikinci el,143.000 TL,https://www.sahibinden.com//ilan/vasita-otomob...
4,mazda,3,1.6 impressive,2010,benzin & lpg,otomatik,218000,105 hp,1598 cc,onden cekis,galeriden,ikinci el,102.000 TL,https://www.sahibinden.com//ilan/vasita-otomob...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,mazda,3,1.6 d touring,2012,dizel,manuel,219000,115 hp,1560 cc,onden cekis,galeriden,ikinci el,110.000 TL,https://www.sahibinden.com//ilan/vasita-otomob...
549,mazda,626,1.6,1990,benzin & lpg,manuel,165381,76 - 100 hp,1301 - 1600 cm3,arkadan itis,sahibinden,ikinci el,36.500 TL,https://www.sahibinden.com//ilan/vasita-otomob...
550,mazda,626,2.0,1998,benzin & lpg,manuel,237000,115 hp,1991 cc,onden cekis,sahibinden,ikinci el,57.500 TL,https://www.sahibinden.com//ilan/vasita-otomob...
551,mazda,3,1.5 skyactive-g reflex,2014,benzin,otomatik,77500,120 hp,1496 cc,onden cekis,sahibinden,ikinci el,214.000 TL,https://www.sahibinden.com//ilan/vasita-otomob...
552,mazda,mx,mx-5 1.5,2018,benzin,manuel,14529,131 hp,1496 cc,arkadan itis,galeriden,ikinci el,349.850 TL,https://www.sahibinden.com//ilan/vasita-otomob...